base_url: /enterprise-guide
title: FOSSLight Enterprise Guide
lang: ko
description: FOSSLight Enterprise Guide

remote_theme: fosslight/guide_theme

#top_link: "https://fosslight.github.io/enterprise-guide-en"
#top_link_word: "English"

addons_title: "FOSSLight Homepage"
addons_url: "https://fosslight.org"

google:
  gtag: G-7EHWGTQYDY
  
readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
